#!/usr/bin/env expect -f
spawn ./target/release/synacor_rs /Users/bencongdon/Downloads/synacor-challenge/challenge.bin

expect "What do you do?"

send "doorway\n"
send "north\n"
send "north\n"
send "bridge\n"
send "continue\n"
send "down\n"
send "east\n"
send "take empty lantern\n"
send "west\n"
send "west\n"
send "passage\n"
send "ladder\n"
send "west\n"
send "south\n"
send "north\n"
send "take can\n"
send "west\n"
send "ladder\n"
send "use can\n"
send "use lantern\n"
send "darkness\n"
send "continue\n"
send "west\n"
send "west\n"
send "west\n"
send "west\n"
send "north\n"
send "take red coin\n"
send "north\n"
send "east\n"
send "take concave coin\n"
send "down\n"
send "take corroded coin\n"
send "up\n"
send "west\n"
send "west\n"
send "take blue coin\n"
send "up\n"
send "take shiny coin\n"
send "down\n"
send "east\n"
send "use blue coin\n"
send "use red coin\n"
send "use shiny coin\n"
send "use concave coin\n"
send "use corroded coin\n"
send "north\n"
send "take teleporter\n"
send "hack_teleporter\n"
send "use teleporter\n"
send "north\n"
send "north\n"
send "north\n"
send "north\n"
send "north\n"
send "north\n"
send "north\n"
send "north\n"
send "north\n"
send "take orb\n"
send "north\n"
send "east\n"
send "east\n"
send "north\n"
send "west\n"
send "south\n"
send "east\n"
send "east\n"
send "west\n"
send "north\n"
send "north\n"
send "east\n"
send "vault\n"
send "take mirror\n"
send "use mirror\n"

expect "Congratulations"
# interact
